### ISSUE TITLE
2024/06/04 22:09:32 ERROR! :Error ReadMessage  websocket: close 1001 (going away)

### ISSUE THREAD

**Issue by Ali-Adnan219** [baxiry/zaradb#21]
![image](https://github.com/baxiry/zaradb/assets/72011889/b837e44b-114c-421c-aee0-14b440e7997e)

**Comment by baxiry** [comment]
Yes. When we reload the page this error occurs. It's a normal thing. But it should not appear in the production version. It should be recorded in the log.
Currently I am showing all errors in standard output. I'll take care of these things in version 0.9
Do you have any better suggestion? I'm interested in your opinion.

**Comment by baxiry** [comment]
This error occurs due to loss of connection from the client, for example after reloading the page.
Yes! It should not appear in standard output. Its normal place is in the log file.

**Comment by baxiry** [comment]
I changed the description. Because this situation is not panic. I was making the wrong description
Thank you.

**Comment by baxiry** [comment]
@Ali-Adnan219  Did you use the pre-built version?

**Comment by Ali-Adnan219** [comment]
> @Ali-Adnan219 Did you use the pre-built version?
No
