### ISSUE TITLE
string in int field -> 0

### ISSUE THREAD

**Issue by baxiry** [baxiry/zaradb#8]
Comparison operators : $gt $lt $gte $lte and $eq handle any string as 0,  for example : 
``` filter:{age: {$gte: 'adam'}} ```

``` adam ``` her is equal 0,

great then , less then is 

see #5

**Comment by baxiry** [comment]
now just $eq $ne are work with string.
every thing else will no work with. it will return : ```nothing match``` result

**Comment by mariusgherasie** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
servatj, @mastepanoski, @JumboLove, @okeeffed, @Gabri, @Ferezoz, @AlpoxDev, @kevyu, @godmode-true, @white-speedy, @dajneem23, @Allen-Ning, @3-juno, @lucasudar, @joshstevens19, @rikhoffbauer, @Methimpact, @monkuo, @everget, @newvladimirov, @Dmitry-Kucher, @wujunchuan, @Cabezaa, @ClemDelp, @twwt, @xiaozuoyou, @gabrielrportugal, @renkelvin, @SadraSamadi, @NotMoni, @zofe, @johnozbay, @biluochun, @mubeenh, @maxclchen, @grospolina, @Buntelrus, @Satcomx00-x00, @jinADS, @iricge, @dooee, @8perezm, @nezdemkovski, @DenisRebenok, @kryptome, @joshelboy, @swcho, @sasikanth513, @AdamyanH, @wellloy1

**Comment by baxiry** [comment]
Update:
The problem has been partially resolved. Two values ​​of the same type can be compared. But not two values ​​with different types.
The result will be unexpected
Since comparing two different types is not possible or rare in actual applications, I will postpone this problem for later.
If you see this as a problem in the real world, leave me a heads up. Thanks

**Comment by baxiry** [comment]
done
